require './app'
require './models/topic'
require './models/question'
require './models/option'
require './models/qa'
require './models/lesson'
require './models/exam'
require './models/level'

Qa.destroy_all
Question.destroy_all
Option.destroy_all
Exam.destroy_all
Level.destroy_all
Lesson.destroy_all
Topic.destroy_all   

topics_data = [
  { topic: 'Flags' },
  { topic: 'Physical Geography' },
  { topic: 'Human Geography' },
  { topic: 'Continents' },
  { topic: 'Oceans and Seas' },
  { topic: 'Capitals' },
  { topic: 'Political Geography' }
]


topics_data.each do |data| 
  topic = Topic.find_or_create_by(topic: data[:topic])
  Lesson.create(title: topic.topic, topic: topic)
end

questions_data = [
  { question: '¿Qué es un país?', correct_option: 'Una entidad territorial y política', topic: 'Physical Geography' },
  { question: '¿Qué es un volcán?', correct_option: 'Una montaña formada por la acumulación de materiales expulsados desde el interior de la Tierra', topic: 'Physical Geography' },
  { question: '¿Cómo se define una capital en geografía?', correct_option: 'Centro administrativo y político de un país o estado.', topic: 'Political Geography' },
  { question: '¿Qué caracteriza a un desierto?', correct_option: 'Una región árida y seca con poca o ninguna vegetación y poca precipitación', topic: 'Physical Geography' },
  { question: '¿Qué es un istmo?', correct_option: 'Una franja estrecha de tierra que conecta dos áreas de tierra más grandes y está rodeada por agua en ambos lados', topic: 'Physical Geography' },
  { question: '¿Cuál es la característica principal de un archipiélago?', correct_option: 'Un grupo o conjunto de islas cercanas entre sí en un cuerpo de agua', topic: 'Physical Geography' },
  { question: '¿Qué es un golfo?', correct_option: 'Una porción de océano o mar parcialmente rodeada por tierra', topic: 'Physical Geography' },
  { question: '¿Cuál es la definición de una isla?', correct_option: 'Una masa de tierra rodeada completamente por agua', topic: 'Physical Geography' },
  { question: '¿Qué es un río?', correct_option: 'Una corriente natural de agua que fluye en una dirección específica a través de la superficie terrestre', topic: 'Physical Geography' },
  { question: '¿Qué son las placas tectónicas en geografía física?', correct_option: 'Son fragmentos de la litosfera terrestre que se mueven sobre el manto terrestre.', topic: 'Physical Geography' },
  { question: '¿Qué es la meteorización?', correct_option: 'El proceso de descomposición y desgaste de rocas y suelo debido a factores como el clima y la acción biológica', topic: 'Physical Geography' },
  { question: '¿Qué son las montañas?', correct_option: 'Elevaciones naturales del terreno que se caracterizan por su altura y relieve escarpado', topic: 'Physical Geography' },
  { question: '¿Qué es la tundra?', correct_option: 'Un bioma frío y árido caracterizado por suelos congelados y vegetación escasa, como musgos y líquenes', topic: 'Physical Geography' },
  { question: '¿Cuál es el proceso de erosión más común en las costas?', correct_option: 'La acción del oleaje y las corrientes marinas', topic: 'Physical Geography' },
  { question: '¿Qué es el permafrost?', correct_option: 'Suelo permanentemente congelado que se encuentra en regiones frías, como el Ártico', topic: 'Physical Geography' },
  { question: '¿Qué es un acuífero?', correct_option: 'Una formación geológica subterránea que almacena y transmite agua subterránea', topic: 'Physical Geography' },
  { question: '¿Cuál es el efecto de la deforestación en el medio ambiente?', correct_option: 'La pérdida de biodiversidad, el cambio climático y la degradación del suelo', topic: 'Physical Geography' },
  { question: '¿Qué son los glaciares?', correct_option: 'Grandes masas de hielo que se forman en tierra y se mueven lentamente debido a la gravedad', topic: 'Physical Geography' },
  { question: '¿Qué es el ciclo del agua?', correct_option: 'El proceso continuo de evaporación, condensación, precipitación y escorrentía que mueve el agua a través del ambiente terrestre', topic: 'Physical Geography' },
  { question: '¿Qué es un ecosistema?', correct_option: 'Una comunidad biológica de organismos vivos interactuando con su entorno físico', topic: 'Physical Geography' },
  { question: '¿Qué es un delta?', correct_option: 'Una acumulación de sedimentos al final de un río, donde el agua fluvial se encuentra con el océano o un cuerpo de agua más grande', topic: 'Physical Geography' },
  { question: '¿Qué es una meseta?', correct_option: 'Una extensa área de terreno plano o ligeramente inclinado elevado sobre la tierra circundante', topic: 'Physical Geography' },
  { question: '¿Qué es un glacial?', correct_option: 'Una gran masa de hielo que se mueve lentamente a través de la superficie de la Tierra debido a la acumulación y compresión de nieve', topic: 'Physical Geography' },
  { question: '¿Qué son los humedales?', correct_option: 'Áreas de tierra que están inundadas de forma permanente o temporal, como pantanos, pantanos y manglares', topic: 'Physical Geography' },
  { question: '¿Qué es un fenómeno natural?', correct_option: 'Un evento o proceso que ocurre en la naturaleza y no es causado por la actividad humana', topic: 'Physical Geography' },
  { question: '¿Qué es un archipiélago?', correct_option: 'Un grupo o cadena de islas dispersas en un cuerpo de agua más grande', topic: 'Physical Geography' },
  { question: '¿Qué es un acantilado?', correct_option: 'Una pared rocosa vertical o inclinada que se encuentra junto a una masa de agua, como un océano o un río', topic: 'Physical Geography' },
  { question: '¿Qué es un fósil?', correct_option: 'Los restos o vestigios de organismos que vivieron en el pasado, conservados en rocas sedimentarias.', topic: 'Physical Geography' },
  { question: '¿Cuál es la definición de lluvia ácida?', correct_option: 'Precipitación atmosférica que contiene altos niveles de ácidos, debido a la combinación de la humedad en el aire con óxidos de azufre y nitrógeno liberados por fuentes naturales y humanas.', topic: 'Physical Geography' },
  { question: '¿Qué es la desertificación?', correct_option: 'La degradación de las tierras áridas, semiáridas y subhúmedas debido a varios factores, como el cambio climático y las actividades humanas, que lleva a la pérdida de la productividad del suelo y la vegetación.', topic: 'Physical Geography' },
  { question: '¿Qué se entiende por línea de costa?', correct_option: 'La línea que marca el límite entre la tierra y el mar en una costa, sujeto a cambios debido a la erosión y la sedimentación.', topic: 'Physical Geography' },
  { question: '¿Qué es la biósfera?', correct_option: 'La capa de la Tierra que sustenta la vida, que incluye la superficie terrestre, los océanos y la atmósfera.', topic: 'Physical Geography' },
  { question: '¿Cuál es la definición de península?', correct_option: 'Una porción de tierra rodeada de agua por tres lados, que se extiende hacia el cuerpo principal de tierra.', topic: 'Physical Geography' },
  { question: '¿Qué es la pluviosidad?', correct_option: 'La cantidad de precipitación medida en un área durante un período específico de tiempo.', topic: 'Physical Geography' },
  { question: '¿Qué es un estuario?', correct_option: 'Un área donde un río se encuentra con el mar, con un flujo y reflujo de agua salada y agua dulce, y un hábitat importante para la vida acuática.', topic: 'Physical Geography' },
  { question: '¿Qué se entiende por continentalidad?', correct_option: 'El grado en que el clima de un área está influenciado por su ubicación lejos del océano y más hacia el interior de una masa de tierra.', topic: 'Physical Geography' },
  { question: '¿Cuál es la definición de precipitación?', correct_option: 'Cualquier forma de agua, líquida o sólida, que cae de la atmósfera y llega a la superficie terrestre.', topic: 'Physical Geography' },
  { question: '¿Qué es un relámpago?', correct_option: 'Una descarga eléctrica visible producida durante una tormenta eléctrica, que resulta de la separación de cargas eléctricas en la atmósfera.', topic: 'Physical Geography' },
  { question: '¿Qué se entiende por afloramiento rocoso?', correct_option: 'Una formación geológica donde las rocas subterráneas son expuestas en la superficie debido a la erosión o la actividad tectónica.', topic: 'Physical Geography' },
  { question: '¿Cuál es la definición de convección?', correct_option: 'El movimiento de fluidos, como aire o agua, causado por diferencias en la temperatura y la densidad, que transporta calor desde una fuente caliente a otra más fría.', topic: 'Physical Geography' },
  { question: '¿Qué es la hidrografía?', correct_option: 'El estudio y la descripción de las aguas superficiales de la Tierra, incluyendo océanos, mares, ríos, lagos y sus características físicas y distribución.', topic: 'Physical Geography' },
  { question: '¿Qué es el clima?', correct_option: 'El patrón promedio del tiempo atmosférico en un área particular, que incluye temperatura, humedad, viento y precipitación, a lo largo de un período prolongado.', topic: 'Physical Geography' },
  { question: '¿Qué son las dunas de arena?', correct_option: 'Montículos o colinas de arena creados por la acción del viento en áreas desérticas o costeras', topic: 'Physical Geography' },
  { question: '¿Qué es una llanura aluvial?', correct_option: 'Una llanura plana o ligeramente inclinada formada por sedimentos depositados por un río durante períodos de inundación', topic: 'Physical Geography' },
  { question: '¿Qué es la tundra?', correct_option: 'Una región fría y árida caracterizada por la falta de árboles, vegetación escasa y suelos congelados gran parte del año', topic: 'Physical Geography' },
  { question: '¿Qué es un atolón?', correct_option: 'Un anillo de coral o islote que rodea una laguna de agua salada en medio del océano', topic: 'Physical Geography' },
  { question: '¿Qué es una cascada?', correct_option: 'Una caída vertical o inclinada de agua en un río o arroyo, a menudo causada por un cambio brusco en el terreno', topic: 'Physical Geography' },
  { question: '¿Qué es un arrecife de coral?', correct_option: 'Una estructura submarina formada por la acumulación de esqueletos de coral y otros organismos marinos', topic: 'Physical Geography' },
  { question: '¿Qué son los fiordos?', correct_option: 'Valles glaciares inundados por el mar, creando una forma de entrante costero con acantilados empinados', topic: 'Physical Geography' },
  { question: '¿Cuál es la función de un estuario?', correct_option: 'Los estuarios actúan como hábitats importantes para la vida marina, proporcionan protección contra inundaciones y erosionan los sedimentos antes de que lleguen al océano', topic: 'Physical Geography' },
  { question: '¿Qué es una cordillera submarina?', correct_option: 'Una cadena de montañas submarinas que se extiende a lo largo del fondo del océano, generalmente formada por actividad volcánica', topic: 'Physical Geography' },
  { question: '¿Cuál es la diferencia entre un delta y una desembocadura?', correct_option: 'Un delta es una acumulación de sedimentos en la desembocadura de un río, mientras que una desembocadura es el punto donde un río se encuentra con otro cuerpo de agua, como un lago o el océano', topic: 'Physical Geography' },
  { question: '¿Qué es una meseta?', correct_option: 'Una región plana y elevada con acantilados escarpados en al menos un lado, a menudo rodeada por tierras más bajas', topic: 'Physical Geography' },
  { question: '¿Qué es un fenómeno meteorológico llamado tornado?', correct_option: 'Es una columna de aire en rotación que se extiende desde una nube de tormenta hasta el suelo, a menudo asociado con vientos destructivos y daños severos', topic: 'Physical Geography' },     
  { question: '¿Qué es la población de un área geográfica?', correct_option: 'El número total de personas que viven en esa área', topic: 'Human Geography' },
  { question: '¿Qué es la cultura en geografía humana?', correct_option: 'Las tradiciones y creencias compartidas por un grupo de personas', topic: 'Human Geography' },
  { question: '¿Qué es la urbanización?', correct_option: 'El proceso de crecimiento y expansión de áreas urbanas', topic: 'Human Geography' },
  { question: '¿Qué es la globalización?', correct_option: 'La integración de las economías, las culturas y las sociedades a nivel mundial', topic: 'Human Geography' },
  { question: '¿Qué estudia la demografía?', correct_option: 'El estudio de las características poblacionales, como el tamaño y la distribución de la población', topic: 'Human Geography' },
  { question: '¿Qué es la industrialización?', correct_option: 'El proceso de transformar una sociedad basada en la agricultura en una sociedad basada en la industria', topic: 'Human Geography' },
  { question: '¿Qué es la pobreza?', correct_option: 'La falta de acceso a recursos básicos como alimentos, vivienda y educación', topic: 'Human Geography' },
  { question: '¿Qué es la diversidad cultural?', correct_option: 'La variedad de grupos étnicos, religiosos y culturales que coexisten en una sociedad', topic: 'Human Geography' },
  { question: '¿Qué es la gentrificación?', correct_option: 'El proceso de renovación urbana que a menudo resulta en el desplazamiento de residentes de bajos ingresos', topic: 'Human Geography' },
  { question: '¿Qué es la migración?', correct_option: 'El movimiento de personas de un lugar a otro con el propósito de establecerse temporal o permanentemente en un nuevo lugar', topic: 'Human Geography' },
  { question: '¿Qué es la geopolítica?', correct_option: 'El estudio de la influencia de factores geográficos en la política y las relaciones internacionales', topic: 'Human Geography' },
  { question: '¿Qué son las ciudades globales?', correct_option: 'Ciudades que desempeñan un papel importante en la economía global y están interconectadas a nivel mundial', topic: 'Human Geography' },
  { question: '¿Qué es el desarrollo sostenible?', correct_option: 'El desarrollo que satisface las necesidades actuales sin comprometer la capacidad de las generaciones futuras para satisfacer sus propias necesidades', topic: 'Human Geography' },
  { question: '¿Qué son los derechos humanos?', correct_option: 'Los derechos fundamentales inherentes a todos los seres humanos, sin importar su nacionalidad, lugar de residencia, sexo, origen nacional o étnico, color, religión, lengua o cualquier otra condición', topic: 'Human Geography' },
  { question: '¿Qué es la migración forzada?', correct_option: 'El movimiento de personas que se ven obligadas a abandonar sus hogares debido a conflictos armados, persecución, desastres naturales u otras circunstancias que ponen en peligro su vida o seguridad', topic: 'Human Geography' },
  { question: '¿Qué es la política de inmigración?', correct_option: 'Las políticas y leyes que regulan la entrada, permanencia y salida de personas de un país', topic: 'Human Geography' },
  { question: '¿Qué es la distribución de la riqueza?', correct_option: 'La forma en que los recursos económicos están repartidos entre los individuos o grupos dentro de una población o una región geográfica', topic: 'Human Geography' },
  { question: '¿Qué es el desarrollo sostenible?', correct_option: 'Un enfoque para satisfacer las necesidades del presente sin comprometer la capacidad de las generaciones futuras para satisfacer sus propias necesidades.', topic: 'Human Geography' },
  { question: '¿Qué es la justicia social?', correct_option: 'La idea de que todas las personas deben tener acceso igualitario a los derechos, oportunidades y recursos dentro de una sociedad', topic: 'Human Geography' },
  { question: '¿Qué son los movimientos sociales?', correct_option: 'Grupos organizados de individuos que trabajan juntos para lograr un cambio social o político en una sociedad', topic: 'Human Geography' },
  { question: '¿Qué es el cambio climático?', correct_option: 'El cambio a largo plazo en los patrones climáticos de la Tierra, generalmente causado por actividades humanas como la quema de combustibles fósiles y la deforestación', topic: 'Human Geography' },
  { question: '¿Qué son los recursos naturales?', correct_option: 'Los materiales y sustancias que se encuentran en la naturaleza y que son valiosos para los seres humanos, como el aire, el agua, los minerales y los bosques', topic: 'Human Geography' },
  { question: '¿Qué es la gestión de recursos naturales?', correct_option: 'El proceso de administrar y conservar los recursos naturales para garantizar su uso sostenible y equitativo', topic: 'Human Geography' },
  { question: '¿Qué es la agricultura de subsistencia?', correct_option: 'Un tipo de agricultura en el que las personas cultivan alimentos principalmente para alimentar a sus propias familias, con poco o ningún excedente para la venta', topic: 'Human Geography' },
  { question: '¿Qué es la agricultura comercial?', correct_option: 'Un tipo de agricultura en el que los productos agrícolas se cultivan principalmente para la venta en el mercado, en lugar de para el consumo personal', topic: 'Human Geography' },
  { question: '¿Qué es la desertificación?', correct_option: 'El proceso por el cual las tierras fértiles se vuelven desérticas debido a la sobreexplotación, la deforestación y otros factores ambientales', topic: 'Human Geography' },
  { question: '¿Qué es la deforestación?', correct_option: 'La eliminación de árboles y bosques para dar paso a otros usos de la tierra, como la agricultura, la ganadería y la urbanización', topic: 'Human Geography' },
  { question: '¿Qué es la contaminación del agua?', correct_option: 'La introducción de sustancias nocivas en cuerpos de agua como ríos, lagos y océanos, generalmente causada por actividades humanas como la industria y la agricultura', topic: 'Human Geography' },
  { question: '¿Qué son los derechos de agua?', correct_option: 'Los derechos legales o de propiedad sobre el uso de agua, que pueden ser otorgados o regulados por los gobiernos para garantizar su uso equitativo y sostenible', topic: 'Human Geography' },
  { question: '¿Qué es la seguridad alimentaria?', correct_option: 'La situación en la que todas las personas tienen acceso físico, social y económico a suficientes alimentos nutritivos para satisfacer sus necesidades dietéticas y preferencias alimentarias para una vida activa y saludable', topic: 'Human Geography' },
  { question: '¿Qué es la tierra cultivable?', correct_option: 'Tierra apta y disponible para la agricultura, que puede ser utilizada para cultivar cultivos y criar ganado', topic: 'Human Geography' },
  { question: '¿Qué es la urbanización descontrolada?', correct_option: 'El crecimiento no planificado y no regulado de áreas urbanas, que puede llevar a problemas como la falta de vivienda, la congestión del tráfico y la contaminación ambiental', topic: 'Human Geography' },
  { question: '¿Qué es la gestión de desastres naturales?', correct_option: 'El proceso de planificación, organización y coordinación de recursos para prepararse y responder a desastres naturales como terremotos, huracanes e inundaciones', topic: 'Human Geography' },
  { question: '¿Qué es la economía informal?', correct_option: 'El sector de la economía que está compuesto por actividades económicas no reguladas o no declaradas, como el trabajo informal y la venta ambulante', topic: 'Human Geography' },
  { question: '¿Qué es la migración interna?', correct_option: 'El movimiento de personas dentro de un país, generalmente desde áreas rurales a áreas urbanas en busca de empleo y oportunidades económicas', topic: 'Human Geography' },
  { question: '¿Qué es el desarrollo económico?', correct_option: 'El proceso de mejora de las condiciones económicas de un país o región, que puede medirse mediante indicadores como el crecimiento del PIB, la reducción de la pobreza y el aumento del empleo', topic: 'Human Geography' },
  { question: '¿Qué es la brecha de desarrollo?', correct_option: 'La diferencia en el desarrollo económico, social y humano entre países o regiones, que puede manifestarse en desigualdades en ingresos, acceso a servicios básicos y calidad de vida', topic: 'Human Geography' },
  { question: '¿Qué son las remesas?', correct_option: 'El dinero que los trabajadores migrantes envían a sus familias en sus países de origen, generalmente para ayudar con los gastos de subsistencia y el desarrollo económico', topic: 'Human Geography' },
  { question: '¿Qué es la planificación urbana?', correct_option: 'El proceso de diseño y regulación del uso del suelo, la infraestructura y el desarrollo de las áreas urbanas para promover un crecimiento urbano sostenible y equitativo', topic: 'Human Geography' },
  { question: '¿Qué es la gentrificación inversa?', correct_option: 'El proceso por el cual áreas urbanas previamente gentrificadas experimentan una reversión demográfica y socioeconómica, atrayendo de nuevo a residentes de bajos ingresos y minorías étnicas', topic: 'Human Geography' },
  { question: '¿Qué es la gobernanza urbana?', correct_option: 'El sistema de toma de decisiones y administración de recursos en áreas urbanas, que involucra a gobiernos locales, organizaciones comunitarias y sectores privados para abordar los desafíos urbanos', topic: 'Human Geography' },
  { question: '¿Qué es la desigualdad de género?', correct_option: 'La disparidad en el acceso, el control y los beneficios de los recursos y oportunidades entre hombres y mujeres, que puede manifestarse en áreas como la educación, el empleo y la representación política', topic: 'Human Geography' },
  { question: '¿Qué es la geografía electoral?', correct_option: 'El estudio de la distribución espacial de los votantes y los resultados electorales, así como los factores geográficos que influyen en el comportamiento político y la participación electoral', topic: 'Human Geography' },
  { question: '¿Qué es la gentrificación cultural?', correct_option: 'El proceso por el cual áreas urbanas experimentan un cambio en su composición étnica y cultural, a menudo resultando en la pérdida de identidad cultural y la expulsión de residentes de bajos ingresos y minorías étnicas', topic: 'Human Geography' },
  { question: '¿Qué es la gestión de residuos?', correct_option: 'El proceso de recolección, tratamiento y disposición final de los desechos sólidos y líquidos, con el objetivo de minimizar el impacto ambiental y promover el reciclaje y la reutilización', topic: 'Human Geography' },
  { question: '¿Qué es la migración forzada?', correct_option: 'El desplazamiento de personas de sus hogares debido a conflictos armados, persecución, desastres naturales u otras condiciones que ponen en peligro su seguridad y bienestar', topic: 'Human Geography' },
  { question: '¿Qué es la gestión del crecimiento urbano?', correct_option: 'El proceso de planificación y regulación del desarrollo físico y socioeconómico de las áreas urbanas, con el fin de garantizar un crecimiento equitativo y sostenible', topic: 'Human Geography' },
  { question: '¿Qué es la densidad de población?', correct_option: 'La medida de cuántas personas viven en un área determinada, generalmente expresada como el número de personas por kilómetro cuadrado o milla cuadrada', topic: 'Human Geography' },
  { question: '¿Qué son los asentamientos informales?', correct_option: 'Áreas urbanas que carecen de servicios básicos y están construidas en terrenos ocupados ilegalmente o no planificados, a menudo habitadas por personas de bajos ingresos y migrantes', topic: 'Human Geography' },
  { question: '¿Dónde se encuentra principalmente el continente de África?', correct_option: 'Mayormente en el hemisferio sur, extendiéndose desde el océano Atlántico en el oeste hasta el océano Índico en el este.', topic: 'Continents' },
  { question: '¿Cuál es la ubicación del continente de América?', correct_option: 'Se extiende desde el océano Ártico en el norte hasta el océano Antártico en el sur, y desde el océano Atlántico en el este hasta el océano Pacífico en el oeste.', topic: 'Continents' },
  { question: '¿Dónde se encuentra el continente de Asia?', correct_option: 'Es el continente más grande y se encuentra en el hemisferio este, limitando al oeste con Europa y África, al sur con el océano Índico, al este con el océano Pacífico y al norte con el océano Ártico.', topic: 'Continents' },
  { question: '¿Qué caracteriza la ubicación del continente de Europa?', correct_option: 'Principalmente en el hemisferio norte, limitada al norte por el océano Ártico, al oeste por el océano Atlántico, al sur por el mar Mediterráneo y al este por Asia.', topic: 'Continents' },
  { question: '¿Dónde se ubica el continente de Oceanía?', correct_option: 'En el hemisferio sur, comprendiendo miles de islas dispersas por el océano Pacífico, incluyendo Australia y Nueva Zelanda.', topic: 'Continents' },
  { question: '¿Cuál es la ubicación de la Antártida?', correct_option: 'Se encuentra en el polo sur de la Tierra y está rodeada por el océano Austral.', topic: 'Continents' },
  { question: '¿Cuál es la posición geográfica del continente de Australia?', correct_option: 'Se encuentra en el hemisferio sur, entre los océanos Índico y Pacífico, al sureste de Asia.', topic: 'Continents' },
  { question: '¿Dónde se localiza principalmente el continente de América del Norte?', correct_option: 'Se encuentra en el hemisferio norte, limitando al norte con el océano Ártico, al este con el océano Atlántico, al oeste con el océano Pacífico y al sur con América Central.', topic: 'Continents' },
  { question: '¿Cuál es la posición relativa del continente de Sudamérica?', correct_option: 'Se ubica en el hemisferio sur, limitando al oeste con el océano Pacífico, al este con el océano Atlántico, al norte con América Central y al sur con la Antártida.', topic: 'Continents' },
  { question: '¿Qué caracteriza la ubicación del continente de América Central?', correct_option: 'Se sitúa entre América del Norte y América del Sur, conectando los dos continentes y limitando al norte con el golfo de México y al sur con Colombia.', topic: 'Continents' },
  { question: '¿Dónde se encuentran principalmente las islas del continente de América Central?', correct_option: 'Principalmente en el mar Caribe y el océano Pacífico, formando un arco entre América del Norte y América del Sur.', topic: 'Continents' },
  { question: '¿Cuál es la ubicación geográfica del continente de África del Norte?', correct_option: 'Se encuentra en el extremo norte del continente africano, limitando con el mar Mediterráneo al norte y con el Sáhara al sur.', topic: 'Continents' },
  { question: '¿Dónde se sitúa principalmente el continente de África del Sur?', correct_option: 'Se encuentra en el extremo sur del continente africano, comprendiendo países como Sudáfrica, Namibia y Botsuana.', topic: 'Continents' },
  { question: '¿Cuál es la posición relativa del continente de Asia Central?', correct_option: 'Se sitúa en la parte central de Asia, rodeada por Rusia al norte, China al este, Irán al sur y Asia del Sur al oeste.', topic: 'Continents' },
  { question: '¿Dónde se localiza principalmente el continente de Asia del Sur?', correct_option: 'Se encuentra en el sur del continente asiático, limitando con el océano Índico al sur y con Asia Central y Asia del Este al norte.', topic: 'Continents' },
  { question: '¿Cuál es la ubicación geográfica del continente de Asia del Este?', correct_option: 'Se sitúa en el este de Asia, limitando con el océano Pacífico al este y con Asia Central y Asia del Sur al oeste.', topic: 'Continents' },
  { question: '¿Dónde se encuentran principalmente las islas del continente de Asia del Este?', correct_option: 'Principalmente en el mar de China Oriental y el mar de Japón, incluyendo islas como Japón, Taiwán y las islas Kuriles.', topic: 'Continents' },
  { question: '¿Cuál es la posición relativa del continente de Europa del Norte?', correct_option: 'Se encuentra en el norte de Europa, limitando con el océano Atlántico al oeste, el mar Báltico al este y Europa Central al sur.', topic: 'Continents' },
  { question: '¿Cuál es la ubicación geográfica del Mar Mediterráneo?', correct_option: 'Se encuentra entre Europa, África y Asia, conectando con el océano Atlántico a través del estrecho de Gibraltar.', topic: 'Oceans' },
  { question: '¿Dónde se sitúa principalmente el Mar de China Meridional?', correct_option: 'Se encuentra al sur de China, entre China continental, Taiwán, Vietnam, Malasia, Filipinas e Indonesia.', topic: 'Oceans' },
  { question: '¿Cuál es la ubicación geográfica del Mar Mediterráneo?', correct_option: 'Se encuentra entre Europa, África y Asia, conectando con el océano Atlántico a través del estrecho de Gibraltar.', topic: 'Oceans' },
  { question: '¿Dónde se sitúa principalmente el Mar de China Meridional?', correct_option: 'Se encuentra al sur de China, entre China continental, Taiwán, Vietnam, Malasia, Filipinas e Indonesia.', topic: 'Oceans' },
  { question: '¿Cuál es la ubicación del Mar Caribe?', correct_option: 'Está ubicado en el marco del océano Atlántico, al sureste del golfo de México y al norte de América del Sur.', topic: 'Oceans' },
  { question: '¿Dónde se localiza principalmente el Mar de Bering?', correct_option: 'Se sitúa entre Alaska y el extremo oriental de Rusia, conectando el océano Pacífico y el océano Ártico.', topic: 'Oceans' },
  { question: '¿Cuál es la posición relativa del Mar de Tasmania?', correct_option: 'Se encuentra al sur de Australia, entre la isla de Tasmania y el continente australiano.', topic: 'Oceans' },
  { question: '¿Dónde se ubica principalmente el Mar del Norte?', correct_option: 'Se sitúa entre Gran Bretaña y Escandinavia, conectando el océano Atlántico con otros mares del norte de Europa.', topic: 'Oceans' },
  { question: '¿Cuál es la ubicación geográfica del Mar de Coral?', correct_option: 'Se encuentra al este de Australia, entre la Gran Barrera de Coral y la costa noreste de Queensland.', topic: 'Oceans' },
  { question: '¿Dónde se encuentra principalmente el Mar de Java?', correct_option: 'Se sitúa entre las islas de Java y Sumatra, en Indonesia, conectando el océano Índico con el mar de China Meridional.', topic: 'Oceans' },
  { question: '¿Cuál es la posición relativa del Mar de Arabia?', correct_option: 'Se encuentra en el noroeste del océano Índico, entre la península arábiga y el subcontinente indio.', topic: 'Oceans' },
  { question: '¿Dónde se localiza principalmente el Mar de Filipinas?', correct_option: 'Se sitúa entre Filipinas y Taiwán, al este del mar de China Meridional.', topic: 'Oceans' },
  { question: '¿Cuál es la ubicación geográfica del Mar de Andamán?', correct_option: 'Se encuentra en el extremo oriental del océano Índico, entre la costa occidental de Tailandia, la península de Malasia y la isla de Andamán.', topic: 'Oceans' },
  { question: '¿Dónde se sitúa principalmente el Mar de Ross?', correct_option: 'Se ubica en la Antártida, al sur del océano Pacífico y al este del mar de Weddell.', topic: 'Oceans' },
  { question: '¿Cuál es la posición relativa del Mar de Weddell?', correct_option: 'Se encuentra en la Antártida, entre la península Antártica y el continente.', topic: 'Oceans' },
  { question: '¿Dónde se localiza principalmente el Mar de Amundsen?', correct_option: 'Se sitúa en la Antártida occidental, al sur del océano Pacífico y al oeste del mar de Ross.', topic: 'Oceans' },
  { question: '¿Cuál es la ubicación geográfica del Mar de Scotia?', correct_option: 'Se encuentra en el océano Atlántico sur, entre América del Sur y la península Antártica.', topic: 'Oceans' },
  { question: '¿Dónde se encuentra principalmente el Mar de Irlanda?', correct_option: 'Se sitúa entre Irlanda y Gran Bretaña, conectando el océano Atlántico con el mar Céltico.', topic: 'Oceans' },
  { question: '¿Cuál es la posición relativa del Mar de Labrador?', correct_option: 'Se encuentra en la costa este de Canadá, entre la isla de Terranova y la región continental de Labrador.', topic: 'Oceans' },
  { question: '¿Cuál es la ubicación del Mar Caribe?', correct_option: 'Está ubicado en el marco del océano Atlántico, al sureste del golfo de México y al norte de América del Sur.', topic: 'Oceans' },
  { question: '¿Dónde se localiza principalmente el Mar de Bering?', correct_option: 'Se sitúa entre Alaska y el extremo oriental de Rusia, conectando el océano Pacífico y el océano Ártico.', topic: 'Oceans' },
  { question: '¿Cuál es la posición relativa del Mar de Tasmania?', correct_option: 'Se encuentra al sur de Australia, entre la isla de Tasmania y el continente australiano.', topic: 'Oceans' },
  { question: '¿Dónde se ubica principalmente el Mar del Norte?', correct_option: 'Se sitúa entre Gran Bretaña y Escandinavia, conectando el océano Atlántico con otros mares del norte de Europa.', topic: 'Oceans' },
  { question: '¿Cuál es la ubicación geográfica del Mar de Coral?', correct_option: 'Se encuentra al este de Australia, entre la Gran Barrera de Coral y la costa noreste de Queensland.', topic: 'Oceans' },
  { question: '¿Dónde se encuentra principalmente el Mar de Java?', correct_option: 'Se sitúa entre las islas de Java y Sumatra, en Indonesia, conectando el océano Índico con el mar de China Meridional.', topic: 'Oceans' },
  { question: '¿Cuál es la posición relativa del Mar de Arabia?', correct_option: 'Se encuentra en el noroeste del océano Índico, entre la península arábiga y el subcontinente indio.', topic: 'Oceans' },
  { question: '¿Dónde se localiza principalmente el Mar de Filipinas?', correct_option: 'Se sitúa entre Filipinas y Taiwán, al este del mar de China Meridional.', topic: 'Oceans' },
  { question: '¿Cuál es la ubicación geográfica del Mar de Andamán?', correct_option: 'Se encuentra en el extremo oriental del océano Índico, entre la costa occidental de Tailandia, la península de Malasia y la isla de Andamán.', topic: 'Oceans' },
  { question: '¿Dónde se sitúa principalmente el Mar de Ross?', correct_option: 'Se ubica en la Antártida, al sur del océano Pacífico y al este del mar de Weddell.', topic: 'Oceans' },
  { question: '¿Cuál es la ubicación geográfica del Océano Pacífico?', correct_option: 'Es el océano más grande, extendiéndose desde el Ártico en el norte hasta el Antártico en el sur, y desde Asia y Australia en el este hasta América en el oeste.', topic: 'Oceans' },
  { question: '¿Dónde se encuentra el Océano Atlántico?', correct_option: 'Entre las Américas al oeste y Europa y África al este.', topic: 'Oceans' },
    { question: '¿Cuál es la capital de Estados Unidos?', correct_option: 'Washington D.C.', topic: 'Capitals', exam: 'Capitales 1' },
  { question: '¿Cuál es la capital de China?', correct_option: 'Pekín', topic: 'Capitals', exam: 'Capitales 2' },
  { question: '¿Cuál es la capital de India?', correct_option: 'Nueva Delhi', topic: 'Capitals', exam: 'Capitales 3' },
  { question: '¿Cuál es la capital de Rusia?', correct_option: 'Moscú', topic: 'Capitals', exam: 'Capitales 4' },
  { question: '¿Cuál es la capital de Brasil?', correct_option: 'Brasilia', topic: 'Capitals', exam: 'Capitales 5' },
  { question: '¿Cuál es la capital de Japón?', correct_option: 'Tokio', topic: 'Capitals', exam: 'Capitales 6' },
  { question: '¿Cuál es la capital de Alemania?', correct_option: 'Berlín', topic: 'Capitals', exam: 'Capitales 1' },
  { question: '¿Cuál es la capital de Reino Unido?', correct_option: 'Londres', topic: 'Capitals', exam: 'Capitales 2' },
  { question: '¿Cuál es la capital de Francia?', correct_option: 'París', topic: 'Capitals', exam: 'Capitales 1' },
  { question: '¿Cuál es la capital de México?', correct_option: 'Ciudad de México', topic: 'Capitals', exam: 'Capitales 3' },
  { question: '¿Cuál es la capital de Italia?', correct_option: 'Roma', topic: 'Capitals', exam: 'Capitales 4' },
  { question: '¿Cuál es la capital de Canadá?', correct_option: 'Ottawa', topic: 'Capitals', exam: 'Capitales 5' },
  { question: '¿Cuál es la capital de Corea del Sur?', correct_option: 'Seúl', topic: 'Capitals', exam: 'Capitales 6' },
  { question: '¿Cuál es la capital de España?', correct_option: 'Madrid', topic: 'Capitals', exam: 'Capitales 1' },
  { question: '¿Cuál es la capital de Australia?', correct_option: 'Camberra', topic: 'Capitals', exam: 'Capitales 2' },
  { question: '¿Cuál es la capital de Indonesia?', correct_option: 'Yakarta', topic: 'Capitals', exam: 'Capitales 3' },
  { question: '¿Cuál es la capital de Países Bajos?', correct_option: 'Ámsterdam', topic: 'Capitals', exam: 'Capitales 4' },
  { question: '¿Cuál es la capital de Arabia Saudita?', correct_option: 'Riad', topic: 'Capitals', exam: 'Capitales 5' },
  { question: '¿Cuál es la capital de Turquía?', correct_option: 'Ankara', topic: 'Capitals', exam: 'Capitales 6' },
  { question: '¿Cuál es la capital de Argentina?', correct_option: 'Buenos Aires', topic: 'Capitals', exam: 'Capitales 1' },
  { question: '¿Cuál es la capital de Sudáfrica?', correct_option: 'Pretoria', topic: 'Capitals', exam: 'Capitales 2' },
  { question: '¿Cuál es la capital de Nigeria?', correct_option: 'Abuja', topic: 'Capitals', exam: 'Capitales 3' },
  { question: '¿Cuál es la capital de Egipto?', correct_option: 'El Cairo', topic: 'Capitals', exam: 'Capitales 4' },
  { question: '¿Cuál es la capital de Pakistán?', correct_option: 'Islamabad', topic: 'Capitals', exam: 'Capitales 5' },
  { question: '¿Cuál es la capital de Irán?', correct_option: 'Teherán', topic: 'Capitals', exam: 'Capitales 6' },
  { question: '¿Cuál es la capital de Vietnam?', correct_option: 'Hanói', topic: 'Capitals', exam: 'Capitales 1' },
  { question: '¿Cuál es la capital de Tailandia?', correct_option: 'Bangkok', topic: 'Capitals', exam: 'Capitales 2' },
    { question: '¿Cuál es la capital de Polonia?', correct_option: 'Varsovia', topic: 'Capitals', exam: 'Capitales 3' },
  { question: '¿Cuál es la capital de Colombia?', correct_option: 'Bogotá', topic: 'Capitals', exam: 'Capitales 4' },
  { question: '¿Cuál es la capital de Venezuela?', correct_option: 'Caracas', topic: 'Capitals', exam: 'Capitales 5' },
  { question: '¿Cuál es la capital de Malasia?', correct_option: 'Kuala Lumpur', topic: 'Capitals', exam: 'Capitales 6' },
  { question: '¿Cuál es la capital de Filipinas?', correct_option: 'Manila', topic: 'Capitals', exam: 'Capitales 1' },
  { question: '¿Cuál es la capital de Bangladesh?', correct_option: 'Daca', topic: 'Capitals', exam: 'Capitales 2' },
  { question: '¿Cuál es la capital de Ucrania?', correct_option: 'Kiev', topic: 'Capitals', exam: 'Capitales 3' },
  { question: '¿Cuál es la capital de Sudán?', correct_option: 'Jartum', topic: 'Capitals', exam: 'Capitales 4' },
  { question: '¿Cuál es la capital de Marruecos?', correct_option: 'Rabat', topic: 'Capitals', exam: 'Capitales 5' },
  { question: '¿Cuál es la capital de Kenia?', correct_option: 'Nairobi', topic: 'Capitals', exam: 'Capitales 6' },
  { question: '¿Cuál es la capital de Perú?', correct_option: 'Lima', topic: 'Capitals', exam: 'Capitales 1' },
  { question: '¿Cuál es la capital de Chile?', correct_option: 'Santiago', topic: 'Capitals', exam: 'Capitales 2' },
  { question: '¿Cuál es la capital de Suecia?', correct_option: 'Estocolmo', topic: 'Capitals', exam: 'Capitales 3' },
  { question: '¿Cuál es la capital de Suiza?', correct_option: 'Berna', topic: 'Capitals', exam: 'Capitales 4' },
  { question: '¿Cuál es la capital de Bélgica?', correct_option: 'Bruselas', topic: 'Capitals', exam: 'Capitales 5' },
  { question: '¿Cuál es la capital de Austria?', correct_option: 'Viena', topic: 'Capitals', exam: 'Capitales 6' },
  { question: '¿Cuál es la capital de Noruega?', correct_option: 'Oslo', topic: 'Capitals', exam: 'Capitales 1' },
  { question: '¿Cuál es la capital de Israel?', correct_option: 'Jerusalén', topic: 'Capitals', exam: 'Capitales 2' },
  { question: '¿Cuál es la capital de Ghana?', correct_option: 'Acra', topic: 'Capitals', exam: 'Capitales 3' },
  { question: '¿Cuál es la capital de Irlanda?', correct_option: 'Dublín', topic: 'Capitals', exam: 'Capitales 4' },
  { question: '¿Cuál es la capital de Finlandia?', correct_option: 'Helsinki', topic: 'Capitals', exam: 'Capitales 5' },
  { question: '¿Cuál es la capital de Portugal?', correct_option: 'Lisboa', topic: 'Capitals', exam: 'Capitales 6' },
  { question: '¿Qué es un país?', correct_option: 'Una entidad política soberana con un territorio definido y un gobierno', topic: 'Political Geography' },
  { question: '¿Qué es una frontera?', correct_option: 'Una línea imaginaria que separa dos países', topic: 'Political Geography' },
  { question: '¿Qué es la diplomacia?', correct_option: 'El proceso de manejar las relaciones internacionales entre países mediante la negociación y el diálogo', topic: 'Political Geography' },
  { question: '¿Qué es una monarquía?', correct_option: 'Un sistema de gobierno en el que un monarca es la cabeza de estado', topic: 'Political Geography' },
  { question: '¿Cuál es la función de un tratado?', correct_option: 'Regular las relaciones entre países', topic: 'Political Geography' },
  { question: '¿Qué es la independencia?', correct_option: 'El estado de libertad y autonomía política de un país o territorio', topic: 'Political Geography' },
  { question: '¿Qué es una alianza?', correct_option: 'Una asociación entre dos o más países con el objetivo de cooperar en áreas específicas de interés común', topic: 'Political Geography' },
  { question: '¿Qué es la colonización?', correct_option: 'El proceso de establecer y controlar territorios por parte de una potencia extranjera', topic: 'Political Geography' },
  { question: '¿Qué es una organización internacional?', correct_option: 'Una entidad formada por países soberanos que trabajan juntos para abordar problemas globales y promover la cooperación internacional', topic: 'Political Geography' },
  { question: '¿Qué es el nacionalismo?', correct_option: 'La ideología que promueve la identidad y los intereses de una nación, a menudo asociada con la aspiración de autodeterminación y soberanía', topic: 'Political Geography' },
  { question: '¿Qué es un gobierno democrático?', correct_option: 'Un sistema de gobierno en el que el poder político es ejercido por el pueblo a través de elecciones libres y justas', topic: 'Political Geography' },
  { question: '¿Qué es la descolonización?', correct_option: 'El proceso de liberación de los territorios coloniales y la adquisición de la independencia política', topic: 'Political Geography' },
  { question: '¿Qué es un embargo?', correct_option: 'Una prohibición oficial impuesta por un país para detener el comercio con otro país como medida de presión política o económica', topic: 'Political Geography' },
  { question: '¿Qué es el derecho internacional?', correct_option: 'El conjunto de normas y principios que regulan las relaciones entre países y otras entidades internacionales', topic: 'Political Geography' },
  { question: '¿Qué es la soberanía?', correct_option: 'El principio de autoridad política y territorial de un estado independiente', topic: 'Political Geography' },
  { question: '¿Qué es un gobierno totalitario?', correct_option: 'Un sistema político en el que el gobierno tiene control absoluto sobre todos los aspectos de la vida pública y privada de los ciudadanos', topic: 'Political Geography' },
  { question: '¿Qué es un refugiado?', correct_option: 'Una persona que ha sido obligada a abandonar su país de origen debido a conflictos, persecución o violaciones de los derechos humanos', topic: 'Political Geography' },
  { question: '¿Qué es la autodeterminación?', correct_option: 'El derecho de los pueblos a decidir su propio estatus político y a determinar libremente su propia forma de gobierno', topic: 'Political Geography' },
  { question: '¿Qué es la diplomacia pública?', correct_option: 'Los esfuerzos de un gobierno para comunicarse y promover sus políticas y valores en el extranjero, dirigidos a la opinión pública internacional', topic: 'Political Geography' },
  { question: '¿Qué es un golpe de Estado?', correct_option: 'La toma violenta o ilegal del poder político por parte de un grupo dentro del gobierno', topic: 'Political Geography' },
  { question: '¿Qué es la asamblea general de las Naciones Unidas?', correct_option: 'El principal órgano deliberativo y representativo de las Naciones Unidas, compuesto por todos los estados miembros', topic: 'Political Geography' },
  { question: '¿Qué es el sistema de partido único?', correct_option: 'Un sistema político en el que solo un partido político está legalmente autorizado para gobernar y monopoliza el poder político', topic: 'Political Geography' },
  { question: '¿Qué es la geopolítica?', correct_option: 'El estudio de la influencia de factores geográficos en la política internacional y las relaciones internacionales', topic: 'Political Geography' },
  { question: '¿Qué es el tratado de libre comercio?', correct_option: 'Un acuerdo entre dos o más países para eliminar barreras comerciales y promover el intercambio de bienes y servicios sin aranceles ni cuotas', topic: 'Political Geography' },
  { question: '¿Qué es la democracia representativa?', correct_option: 'Un sistema político en el que los ciudadanos eligen representantes para que tomen decisiones en su nombre en el gobierno', topic: 'Political Geography' },
  { question: '¿Qué es la cumbre internacional?', correct_option: 'Una reunión de líderes y representantes de varios países para discutir y tomar decisiones sobre temas de interés común', topic: 'Political Geography' },
  { question: '¿Qué es la asamblea constituyente?', correct_option: 'Un cuerpo legislativo especial encargado de redactar o revisar una constitución para un país o territorio', topic: 'Political Geography' },
  { question: '¿Qué es el gobierno de coalición?', correct_option: 'Un gobierno formado por dos o más partidos políticos que trabajan juntos para formar una mayoría en el parlamento y gobernar el país', topic: 'Political Geography' },
  { question: '¿Qué es la neutralidad?', correct_option: 'La política de un país de no tomar partido en conflictos internacionales y mantenerse imparcial', topic: 'Political Geography' },
  { question: '¿Qué es el federalismo?', correct_option: 'Un sistema de gobierno en el que el poder está dividido entre un gobierno central y unidades políticas más pequeñas, como estados o provincias', topic: 'Political Geography' },
  { question: '¿Qué es el imperialismo?', correct_option: 'La política de extender el control o la influencia de una nación sobre territorios extranjeros mediante la colonización, la conquista o la dominación económica', topic: 'Political Geography' },
  { question: '¿Qué es el bloque regional?', correct_option: 'Una asociación de países en una región geográfica que se unen para promover la cooperación económica y política', topic: 'Political Geography' },
  { question: '¿Qué es la insurgencia?', correct_option: 'La rebelión armada de un grupo contra un gobierno establecido, a menudo por motivos políticos o sociales', topic: 'Political Geography' },
  { question: '¿Qué es un estado fallido?', correct_option: 'Un país que ha perdido el control efectivo sobre su territorio y no puede mantener el orden interno ni brindar servicios básicos a su población', topic: 'Political Geography' },
  { question: '¿Qué es la anexión territorial?', correct_option: 'El acto de agregar un territorio a otro país mediante la conquista, el tratado o la ocupación militar', topic: 'Political Geography' },
  { question: '¿Qué es el sufragio universal?', correct_option: 'El derecho de todos los ciudadanos adultos a votar en elecciones políticas', topic: 'Political Geography' },
  { question: '¿Qué es la constitución?', correct_option: 'Un conjunto de principios y leyes fundamentales que establecen la estructura del gobierno y los derechos de los ciudadanos en un país', topic: 'Political Geography' },
  { question: '¿Qué es la geopolítica energética?', correct_option: 'El estudio de las relaciones entre el poder político y los recursos energéticos, como el petróleo y el gas natural, a nivel nacional e internacional', topic: 'Political Geography' },
  { question: '¿Qué es la guerra fría?', correct_option: 'El período de tensión política y confrontación ideológica entre los Estados Unidos y la Unión Soviética después de la Segunda Guerra Mundial, sin un conflicto militar directo', topic: 'Political Geography' },
  { question: '¿Qué es un bloqueo económico?', correct_option: 'Una medida coercitiva en la que un país restringe o prohíbe el comercio con otro país como forma de presión política o económica', topic: 'Political Geography' },
  { question: '¿Qué es la soberanía nacional?', correct_option: 'El principio de autoridad política y autonomía de un estado en su territorio, sin interferencia externa', topic: 'Political Geography' },
  { question: '¿Qué es la legislatura?', correct_option: 'El cuerpo legislativo encargado de hacer leyes en un país o estado', topic: 'Political Geography' },
  { question: '¿Qué es la economía de mercado?', correct_option: 'Un sistema económico en el que los precios de los bienes y servicios son determinados por la oferta y la demanda en el mercado, con una mínima interferencia del gobierno', topic: 'Political Geography' },
  { question: '¿Qué es el apartheid?', correct_option: 'El sistema de segregación racial y discriminación institucionalizada que existió en Sudáfrica entre 1948 y 1994', topic: 'Political Geography' },
  { question: '¿Qué es la globalización?', correct_option: 'El proceso de interconexión e interdependencia creciente entre las economías, las sociedades y las culturas a nivel mundial', topic: 'Political Geography' },
  { question: '¿Qué es el nacionalismo étnico?', correct_option: 'La identificación y lealtad hacia un grupo étnico particular como base de la identidad nacional y política', topic: 'Political Geography' },
  { question: '¿Qué es la diplomacia multilateral?', correct_option: 'El proceso de negociación y cooperación entre tres o más países para abordar problemas y desafíos comunes', topic: 'Political Geography' },
  { question: '¿Qué es un referéndum?', correct_option: 'Una votación en la que los ciudadanos expresan su opinión sobre una cuestión específica, generalmente de importancia nacional', topic: 'Political Geography' },  
  { question: '¿Qué es un tratado internacional?', correct_option: 'Un acuerdo formal entre dos o más países que establece derechos y obligaciones mutuos bajo el derecho internacional', topic: 'Political Geography' },
    #So Easy Mode
  #{ correct_option: 'Argentina', topic: 'Flags-1', imagepath: 'images/flags/ar.svg' },
  #{ correct_option: 'Bolivia', topic: 'Flags-1', imagepath: 'images/flags/bo.svg' },
  #{ correct_option: 'Brasil', topic: 'Flags-1', imagepath: 'images/flags/br.svg' },
  #{ correct_option: 'Canadá', topic: 'Flags-1', imagepath: 'images/flags/ca.svg' },
  #{ correct_option: 'Chile', topic: 'Flags-1', imagepath: 'images/flags/cl.svg' },
  #{ correct_option: 'China', topic: 'Flags-1', imagepath: 'images/flags/cn.svg' },
  #{ correct_option: 'Colombia', topic: 'Flags-1', imagepath: 'images/flags/co.svg' },
  #{ correct_option: 'Costa Rica', topic: 'Flags-1', imagepath: 'images/flags/cr.svg' },
  #{ correct_option: 'Croacia', topic: 'Flags-1', imagepath: 'images/flags/hr.svg' },
  #{ correct_option: 'Cuba', topic: 'Flags-1', imagepath: 'images/flags/cu.svg' },
  #{ correct_option: 'Ecuador', topic: 'Flags-1', imagepath: 'images/flags/ec.svg' },
  #{ correct_option: 'Francia', topic: 'Flags-1', imagepath: 'images/flags/fr.svg' },
  #{ correct_option: 'Alemania', topic: 'Flags-1', imagepath: 'images/flags/de.svg' },
  #{ correct_option: 'Italia', topic: 'Flags-1', imagepath: 'images/flags/it.svg' },
  #{ correct_option: 'Japón', topic: 'Flags-1', imagepath: 'images/flags/jp.svg' },
  #{ correct_option: 'México', topic: 'Flags-1', imagepath: 'images/flags/mx.svg' },
  #{ correct_option: 'Portugal', topic: 'Flags-1', imagepath: 'images/flags/pt.svg' },
  #{ correct_option: 'Perú', topic: 'Flags-1', imagepath: 'images/flags/pe.svg' },
  #{ correct_option: 'España', topic: 'Flags-1', imagepath: 'images/flags/es.svg' },
  #{ correct_option: 'Uruguay', topic: 'Flags-1', imagepath: 'images/flags/uy.svg' },
  #{ correct_option: 'Reino Unido', topic: 'Flags-1', imagepath: 'images/flags/gb.svg' },
  #{ correct_option: 'Estados Unidos de América', topic: 'Flags-1', imagepath: 'images/flags/us.svg' },
  #{ correct_option: 'Venezuela', topic: 'Flags-1', imagepath: 'images/flags/ve.svg' },
  #{ correct_option: 'Paraguay', topic: 'Flags-1', imagepath: 'images/flags/py.svg' },
  #{ correct_option: 'Puerto Rico', topic: 'Flags-1', imagepath: 'images/flags/pr.svg' },
  #{ correct_option: 'Honduras', topic: 'Flags-1', imagepath: 'images/flags/hn.svg' },

  ##Easy mode

  #{ correct_option: 'Argelia', topic: 'Flags-2', imagepath: 'images/flags/dz.svg' },
  #{ correct_option: 'Bélgica', topic: 'Flags-2', imagepath: 'images/flags/be.svg' },
  #{ correct_option: 'Bosnia y Herzegovina', topic: 'Flags-2', imagepath: 'images/flags/ba.svg' },
  #{ correct_option: 'Camerún', topic: 'Flags-2', imagepath: 'images/flags/cm.svg' },
  #{ correct_option: 'Dominica', topic: 'Flags-2', imagepath: 'images/flags/dm.svg' },
  #{ correct_option: 'República Dominicana', topic: 'Flags-2', imagepath: 'images/flags/do.svg' },
  #{ correct_option: 'El Salvador', topic: 'Flags-2', imagepath: 'images/flags/sv.svg' },
  #{ correct_option: 'Finlandia', topic: 'Flags-2', imagepath: 'images/flags/fi.svg' },
  #{ correct_option: 'Ghana', topic: 'Flags-2', imagepath: 'images/flags/gh.svg' },
  #{ correct_option: 'Grecia', topic: 'Flags-2', imagepath: 'images/flags/gr.svg' },
  #{ correct_option: 'Guatemala', topic: 'Flags-2', imagepath: 'images/flags/gt.svg' },
  #{ correct_option: 'India', topic: 'Flags-2', imagepath: 'images/flags/in.svg' },
  #{ correct_option: 'Irán', topic: 'Flags-2', imagepath: 'images/flags/ir.svg' },
  #{ correct_option: 'Israel', topic: 'Flags-2', imagepath: 'images/flags/il.svg' },
  #{ correct_option: 'Jamaica', topic: 'Flags-2', imagepath: 'images/flags/jm.svg' },
  #{ correct_option: 'Países Bajos', topic: 'Flags-2', imagepath: 'images/flags/nl.svg' },
  #{ correct_option: 'Nueva Zelanda', topic: 'Flags-2', imagepath: 'images/flags/nz.svg' },
  #{ correct_option: 'Nicaragua', topic: 'Flags-2', imagepath: 'images/flags/ni.svg' },
  #{ correct_option: 'Nigeria', topic: 'Flags-2', imagepath: 'images/flags/ng.svg' },
  #{ correct_option: 'Polonia', topic: 'Flags-2', imagepath: 'images/flags/pl.svg' },
  #{ correct_option: 'Rusia', topic: 'Flags-2', imagepath: 'images/flags/ru.svg' },
  #{ correct_option: 'Arabia Saudita', topic: 'Flags-2', imagepath: 'images/flags/sa.svg' },
  #{ correct_option: 'Senegal', topic: 'Flags-2', imagepath: 'images/flags/sn.svg' },
  #{ correct_option: 'Serbia', topic: 'Flags-2', imagepath: 'images/flags/rs.svg' },
  #{ correct_option: 'Corea del Sur', topic: 'Flags-2', imagepath: 'images/flags/kr.svg' },
  #{ correct_option: 'Panamá', topic: 'Flags-2', imagepath: 'images/flags/pa.svg' },

  ##Medium Mode

  #{ correct_option: 'Andorra', topic: 'Flags-3', imagepath: 'images/flags/ad.svg' },
  #{ correct_option: 'Australia', topic: 'Flags-3', imagepath: 'images/flags/au.svg' },
  #{ correct_option: 'Bulgaria', topic: 'Flags-3', imagepath: 'images/flags/bg.svg' },
  #{ correct_option: 'Egipto', topic: 'Flags-3', imagepath: 'images/flags/eg.svg' },
  #{ correct_option: 'Estonia', topic: 'Flags-3', imagepath: 'images/flags/ee.svg' },
  #{ correct_option: 'Dinamarca', topic: 'Flags-3', imagepath: 'images/flags/dk.svg' },
  #{ correct_option: 'Georgia', topic: 'Flags-3', imagepath: 'images/flags/ge.svg' },
  #{ correct_option: 'Haití', topic: 'Flags-3', imagepath: 'images/flags/ht.svg' },
  #{ correct_option: 'Hungría', topic: 'Flags-3', imagepath: 'images/flags/hu.svg' },
  #{ correct_option: 'Islandia', topic: 'Flags-3', imagepath: 'images/flags/is.svg' },
  #{ correct_option: 'Indonesia', topic: 'Flags-3', imagepath: 'images/flags/id.svg' },
  #{ correct_option: 'Irak', topic: 'Flags-3', imagepath: 'images/flags/iq.svg' },
  #{ correct_option: 'Irlanda', topic: 'Flags-3', imagepath: 'images/flags/ie.svg' },
  #{ correct_option: 'Kenia', topic: 'Flags-3', imagepath: 'images/flags/ke.svg' },
  #{ correct_option: 'Luxemburgo', topic: 'Flags-3', imagepath: 'images/flags/lu.svg' },
  #{ correct_option: 'Madagascar', topic: 'Flags-3', imagepath: 'images/flags/mg.svg' },
  #{ correct_option: 'Mónaco', topic: 'Flags-3', imagepath: 'images/flags/mc.svg' },
  #{ correct_option: 'Ucrania', topic: 'Flags-3', imagepath: 'images/flags/ua.svg' },
  #{ correct_option: 'Corea del Norte', topic: 'Flags-3', imagepath: 'images/flags/kp.svg' },
  #{ correct_option: 'Pakistán', topic: 'Flags-3', imagepath: 'images/flags/pk.svg' },
  #{ correct_option: 'Hong Kong', topic: 'Flags-3', imagepath: 'images/flags/hk.svg' },
  #{ correct_option: 'Filipinas', topic: 'Flags-3', imagepath: 'images/flags/ph.svg' },
  #{ correct_option: 'Catar', topic: 'Flags-3', imagepath: 'images/flags/qa.svg' },
  #{ correct_option: 'Sudáfrica', topic: 'Flags-3', imagepath: 'images/flags/za.svg' },
  #{ correct_option: 'Suecia', topic: 'Flags-3', imagepath: 'images/flags/se.svg' },
  #{ correct_option: 'Suiza', topic: 'Flags-3', imagepath: 'images/flags/ch.svg' },

  ##Semi-hard mode

  #{ correct_option: 'San Marino', topic: 'Flags-4', imagepath: 'images/flags/sm.svg' },
  #{ correct_option: 'Montenegro', topic: 'Flags-4', imagepath: 'images/flags/me.svg' },
  #{ correct_option: 'Nepal', topic: 'Flags-4', imagepath: 'images/flags/np.svg' },
  #{ correct_option: 'Zambia', topic: 'Flags-4', imagepath: 'images/flags/zm.svg' },
  #{ correct_option: 'Turquía', topic: 'Flags-4', imagepath: 'images/flags/tr.svg' },
  #{ correct_option: 'Yemen', topic: 'Flags-4', imagepath: 'images/flags/ye.svg' },
  #{ correct_option: 'Afganistán', topic: 'Flags-4', imagepath: 'images/flags/af.svg' },
  #{ correct_option: 'Albania', topic: 'Flags-4', imagepath: 'images/flags/al.svg' },
  #{ correct_option: 'Angola', topic: 'Flags-4', imagepath: 'images/flags/ao.svg' },
  #{ correct_option: 'República Checa', topic: 'Flags-4', imagepath: 'images/flags/cz.svg' },
  #{ correct_option: 'Guinea', topic: 'Flags-4', imagepath: 'images/flags/gn.svg' },
  #{ correct_option: 'Malí', topic: 'Flags-4', imagepath: 'images/flags/ml.svg' },
  #{ correct_option: 'Moldavia', topic: 'Flags-4', imagepath: 'images/flags/md.svg' },
  #{ correct_option: 'Mongolia', topic: 'Flags-4', imagepath: 'images/flags/mn.svg' },
  #{ correct_option: 'Marruecos', topic: 'Flags-4', imagepath: 'images/flags/ma.svg' },
  #{ correct_option: 'Namibia', topic: 'Flags-4', imagepath: 'images/flags/na.svg' },
  #{ correct_option: 'Níger', topic: 'Flags-4', imagepath: 'images/flags/ne.svg' },
  #{ correct_option: 'República del Congo', topic: 'Flags-4', imagepath: 'images/flags/cg.svg' },
  #{ correct_option: 'Rumania', topic: 'Flags-4', imagepath: 'images/flags/ro.svg' },
  #{ correct_option: 'Eslovaquia', topic: 'Flags-4', imagepath: 'images/flags/sk.svg' },
  #{ correct_option: 'Eslovenia', topic: 'Flags-4', imagepath: 'images/flags/si.svg' },
  #{ correct_option: 'Taiwán', topic: 'Flags-4', imagepath: 'images/flags/tw.svg' },
  #{ correct_option: 'Tailandia', topic: 'Flags-4', imagepath: 'images/flags/th.svg' },
  #{ correct_option: 'Vietnam', topic: 'Flags-4', imagepath: 'images/flags/vn.svg' },
  #{ correct_option: 'Omán', topic: 'Flags-4', imagepath: 'images/flags/om.svg' },
  #{ correct_option: 'Emiratos Árabes Unidos', topic: 'Flags-4', imagepath: 'images/flags/ae.svg' },

  ##Hard mode

  #{ correct_option: 'Belice', topic: 'Flags-5', imagepath: 'images/flags/bz.svg' },
  #{ correct_option: 'Cabo Verde', topic: 'Flags-5', imagepath: 'images/flags/cv.svg' },
  #{ correct_option: 'Etiopía', topic: 'Flags-5', imagepath: 'images/flags/et.svg' },
  #{ correct_option: 'Fiyi', topic: 'Flags-5', imagepath: 'images/flags/fj.svg' },
  #{ correct_option: 'Gibraltar', topic: 'Flags-5', imagepath: 'images/flags/gi.svg' },
  #{ correct_option: 'Groenlandia', topic: 'Flags-5', imagepath: 'images/flags/gl.svg' },
  #{ correct_option: 'Kazajistán', topic: 'Flags-5', imagepath: 'images/flags/kz.svg' },
  #{ correct_option: 'Kuwait', topic: 'Flags-5', imagepath: 'images/flags/kw.svg' },
  #{ correct_option: 'Liberia', topic: 'Flags-5', imagepath: 'images/flags/lr.svg' },
  #{ correct_option: 'Libia', topic: 'Flags-5', imagepath: 'images/flags/ly.svg' },
  #{ correct_option: 'Macedonia del Norte', topic: 'Flags-5', imagepath: 'images/flags/mk.svg' },
  #{ correct_option: 'Singapur', topic: 'Flags-5', imagepath: 'images/flags/sg.svg' },
  #{ correct_option: 'Somalia', topic: 'Flags-5', imagepath: 'images/flags/so.svg' },
  #{ correct_option: 'Sudán del Sur', topic: 'Flags-5', imagepath: 'images/flags/ss.svg' },
  #{ correct_option: 'Sudán', topic: 'Flags-5', imagepath: 'images/flags/sd.svg' },
  #{ correct_option: 'Siria', topic: 'Flags-5', imagepath: 'images/flags/sy.svg' },
  #{ correct_option: 'Uganda', topic: 'Flags-5', imagepath: 'images/flags/ug.svg' },
  #{ correct_option: 'Bangladesh', topic: 'Flags-5', imagepath: 'images/flags/bd.svg' },
  #{ correct_option: 'Trinidad y Tobago', topic: 'Flags-5', imagepath: 'images/flags/tt.svg' },
  #{ correct_option: 'Túnez', topic: 'Flags-5', imagepath: 'images/flags/tn.svg' },
  #{ correct_option: 'Estado de Palestina', topic: 'Flags-5', imagepath: 'images/flags/ps.svg' },
  #{ correct_option: 'Armenia', topic: 'Flags-5', imagepath: 'images/flags/am.svg' },
  #{ correct_option: 'Austria', topic: 'Flags-5', imagepath: 'images/flags/at.svg' },

  ##Demential 1

  #{ correct_option: 'Islas Malvinas', topic: 'Flags-6', imagepath: 'images/flags/fk.svg' },
  #{ correct_option: 'Kirguistán', topic: 'Flags-6', imagepath: 'images/flags/kg.svg' },
  #{ correct_option: 'Burkina Faso', topic: 'Flags-6', imagepath: 'images/flags/bf.svg' },
  #{ correct_option: 'República Democrática del Congo', topic: 'Flags-6', imagepath: 'images/flags/cd.svg' },
  #{ correct_option: 'Anguila', topic: 'Flags-6', imagepath: 'images/flags/ai.svg' },
  #{ correct_option: 'Polinesia Francesa', topic: 'Flags-6', imagepath: 'images/flags/pf.svg' },
  #{ correct_option: 'Jordania', topic: 'Flags-6', imagepath: 'images/flags/jo.svg' },
  #{ correct_option: 'Territorios Franceses del Sur', topic: 'Flags-6', imagepath: 'images/flags/tf.svg' },
  #{ correct_option: 'San Vicente y las Granadinas', topic: 'Flags-6', imagepath: 'images/flags/vc.svg' },
  #{ correct_option: 'Aruba', topic: 'Flags-6', imagepath: 'images/flags/aw.svg' },
  #{ correct_option: 'Eritrea', topic: 'Flags-6', imagepath: 'images/flags/er.svg' },
  #{ correct_option: 'Turkmenistán', topic: 'Flags-6', imagepath: 'images/flags/tm.svg' },
  #{ correct_option: 'Nauru', topic: 'Flags-6', imagepath: 'images/flags/nr.svg' },
  #{ correct_option: 'Isla Bouvet', topic: 'Flags-6', imagepath: 'images/flags/bv.svg' },
  #{ correct_option: 'Letonia', topic: 'Flags-6', imagepath: 'images/flags/lv.svg' },
  #{ correct_option: 'Baréin', topic: 'Flags-6', imagepath: 'images/flags/bh.svg' },
  #{ correct_option: 'Svalbard y Jan Mayen', topic: 'Flags-6', imagepath: 'images/flags/sj.svg' },
  #{ correct_option: 'Chad', topic: 'Flags-6', imagepath: 'images/flags/td.svg' },
  #{ correct_option: 'Antártida', topic: 'Flags-6', imagepath: 'images/flags/aq.svg' },
  #{ correct_option: 'Islas Vírgenes de los Estados Unidos', topic: 'Flags-6', imagepath: 'images/flags/vi.svg' },
  #{ correct_option: 'Guinea-Bisáu', topic: 'Flags-6', imagepath: 'images/flags/gw.svg' },
  #{ correct_option: 'Pitcairn', topic: 'Flags-6', imagepath: 'images/flags/pn.svg' },
  #{ correct_option: 'Benín', topic: 'Flags-6', imagepath: 'images/flags/bj.svg' },
  #{ correct_option: 'Santa Sede', topic: 'Flags-6', imagepath: 'images/flags/va.svg' },
  #{ correct_option: 'Guam', topic: 'Flags-6', imagepath: 'images/flags/gu.svg' },

  ##Demential 2

  #{ correct_option: 'Mauritania', topic: 'Flags-7', imagepath: 'images/flags/mr.svg' },
  #{ correct_option: 'Territorio Británico del Océano Índico', topic: 'Flags-7', imagepath: 'images/flags/io.svg' },
  #{ correct_option: 'Liechtenstein', topic: 'Flags-7', imagepath: 'images/flags/li.svg' },
  #{ correct_option: 'Bermudas', topic: 'Flags-7', imagepath: 'images/flags/bm.svg' },
  #{ correct_option: 'Estados Federados de Micronesia', topic: 'Flags-7', imagepath: 'images/flags/fm.svg' },
  #{ correct_option: 'Surinam', topic: 'Flags-7', imagepath: 'images/flags/sr.svg' },
  #{ correct_option: 'Brunéi', topic: 'Flags-7', imagepath: 'images/flags/bn.svg' },
  #{ correct_option: 'Reunión', topic: 'Flags-7', imagepath: 'images/flags/re.svg' },
  #{ correct_option: 'Samoa', topic: 'Flags-7', imagepath: 'images/flags/ws.svg' },
  #{ correct_option: 'Islas Heard y McDonald', topic: 'Flags-7', imagepath: 'images/flags/hm.svg' },
  #{ correct_option: 'Camboya', topic: 'Flags-7', imagepath: 'images/flags/kh.svg' },
  #{ correct_option: 'Isla Norfolk', topic: 'Flags-7', imagepath: 'images/flags/nf.svg' },
  #{ correct_option: 'San Cristóbal y Nieves', topic: 'Flags-7', imagepath: 'images/flags/kn.svg' },
  #{ correct_option: 'Montserrat', topic: 'Flags-7', imagepath: 'images/flags/ms.svg' },
  #{ correct_option: 'Malasia', topic: 'Flags-7', imagepath: 'images/flags/my.svg' },
  #{ correct_option: 'Malta', topic: 'Flags-7', imagepath: 'images/flags/mt.svg' },
  #{ correct_option: 'San Pedro y Miquelón', topic: 'Flags-7', imagepath: 'images/flags/pm.svg' },
  #{ correct_option: 'Niue', topic: 'Flags-7', imagepath: 'images/flags/nu.svg' },
  #{ correct_option: 'Isla de Man', topic: 'Flags-7', imagepath: 'images/flags/im.svg' },
  #{ correct_option: 'eSwatini', topic: 'Flags-7', imagepath: 'images/flags/sz.svg' },
  #{ correct_option: 'Suecia', topic: 'Flags-7', imagepath: 'images/flags/se.svg' },
  #{ correct_option: 'Maldivas', topic: 'Flags-7', imagepath: 'images/flags/mv.svg' },
  #{ correct_option: 'Tayikistán', topic: 'Flags-7', imagepath: 'images/flags/tj.svg' },
  #{ correct_option: 'Guernsey', topic: 'Flags-7', imagepath: 'images/flags/gg.svg' },

  ##Demential 3

  #{ correct_option: 'Islas Turcas y Caicos', topic: 'Flags-8', imagepath: 'images/flags/tc.svg' },
  #{ correct_option: 'Islas Menores Alejadas de los Estados Unidos', topic: 'Flags-8', imagepath: 'images/flags/um.svg' },
  #{ correct_option: 'Yibuti', topic: 'Flags-8', imagepath: 'images/flags/dj.svg' },
  #{ correct_option: 'San Bartolomé', topic: 'Flags-8', imagepath: 'images/flags/bl.svg' },
  #{ correct_option: 'Martinica', topic: 'Flags-8', imagepath: 'images/flags/mq.svg' },
  #{ correct_option: 'Islas Vírgenes Británicas', topic: 'Flags-8', imagepath: 'images/flags/vg.svg' },
  #{ correct_option: 'Mozambique', topic: 'Flags-8', imagepath: 'images/flags/mz.svg' },
  #{ correct_option: 'Sahara Occidental', topic: 'Flags-8', imagepath: 'images/flags/eh.svg' },
  #{ correct_option: 'Antigua y Barbuda', topic: 'Flags-8', imagepath: 'images/flags/ag.svg' },
  #{ correct_option: 'Sri Lanka', topic: 'Flags-8', imagepath: 'images/flags/lk.svg' },
  #{ correct_option: 'Botsuana', topic: 'Flags-8', imagepath: 'images/flags/bw.svg' },
  #{ correct_option: 'Tonga', topic: 'Flags-8', imagepath: 'images/flags/to.svg' },
  #{ correct_option: 'Uzbekistán', topic: 'Flags-8', imagepath: 'images/flags/uz.svg' },
  #{ correct_option: 'Granada', topic: 'Flags-8', imagepath: 'images/flags/gd.svg' },
  #{ correct_option: 'República Árabe Siria', topic: 'Flags-8', imagepath: 'images/flags/sy.svg' },
  #{ correct_option: 'Curazao', topic: 'Flags-8', imagepath: 'images/flags/cw.svg' },
  #{ correct_option: 'Mauricio', topic: 'Flags-8', imagepath: 'images/flags/mu.svg' },
  #{ correct_option: 'Tanzania', topic: 'Flags-8', imagepath: 'images/flags/tz.svg' },
  #{ correct_option: 'Jersey', topic: 'Flags-8', imagepath: 'images/flags/je.svg' },
  #{ correct_option: 'Gambia', topic: 'Flags-8', imagepath: 'images/flags/gm.svg' },
  #{ correct_option: 'Islas Feroe', topic: 'Flags-8', imagepath: 'images/flags/fo.svg' },
  #{ correct_option: 'Nueva Caledonia', topic: 'Flags-8', imagepath: 'images/flags/nc.svg' },
  #{ correct_option: 'Myanmar', topic: 'Flags-8', imagepath: 'images/flags/mm.svg' },
  #{ correct_option: 'Islas Salomón', topic: 'Flags-8', imagepath: 'images/flags/sb.svg' },
  #{ correct_option: 'Laos', topic: 'Flags-8', imagepath: 'images/flags/la.svg' },

  ##Demential 4

  #{ correct_option: 'Samoa Americana', topic: 'Flags-9', imagepath: 'images/flags/as.svg' },
  #{ correct_option: 'Chipre', topic: 'Flags-9', imagepath: 'images/flags/cy.svg' },
  #{ correct_option: 'Guayana Francesa', topic: 'Flags-9', imagepath: 'images/flags/gf.svg' },
  #{ correct_option: 'Vanuatu', topic: 'Flags-9', imagepath: 'images/flags/vu.svg' },
  #{ correct_option: 'Georgia del Sur y las Islas Sandwich del Sur', topic: 'Flags-9', imagepath: 'images/flags/gs.svg' },
  #{ correct_option: 'Sierra Leona', topic: 'Flags-9', imagepath: 'images/flags/sl.svg' },
  #{ correct_option: 'Líbano', topic: 'Flags-9', imagepath: 'images/flags/lb.svg' },
  #{ correct_option: 'Comoras', topic: 'Flags-9', imagepath: 'images/flags/km.svg' },
  #{ correct_option: 'Timor Oriental', topic: 'Flags-9', imagepath: 'images/flags/tl.svg' },
  #{ correct_option: 'Mayotte', topic: 'Flags-9', imagepath: 'images/flags/yt.svg' },
  #{ correct_option: 'Guadalupe', topic: 'Flags-9', imagepath: 'images/flags/gp.svg' },
  #{ correct_option: 'Islas Cocos (Keeling)', topic: 'Flags-9', imagepath: 'images/flags/cc.svg' },
  #{ correct_option: 'Wallis y Futuna', topic: 'Flags-9', imagepath: 'images/flags/wf.svg' },
  #{ correct_option: 'Caribe Neerlandés', topic: 'Flags-9', imagepath: 'images/flags/bq.svg' },
  #{ correct_option: 'Lesoto', topic: 'Flags-9', imagepath: 'images/flags/ls.svg' },
  #{ correct_option: 'Palaos', topic: 'Flags-9', imagepath: 'images/flags/pw.svg' },
  #{ correct_option: 'Tokelau', topic: 'Flags-9', imagepath: 'images/flags/tk.svg' },
  #{ correct_option: 'Santa Elena, Ascensión y Tristán de Acuña', topic: 'Flags-9', imagepath: 'images/flags/sh.svg' },
  #{ correct_option: 'Papúa Nueva Guinea', topic: 'Flags-9', imagepath: 'images/flags/pg.svg' },
  #{ correct_option: 'Bielorrusia', topic: 'Flags-9', imagepath: 'images/flags/by.svg' },
  #{ correct_option: 'Santa Lucía', topic: 'Flags-9', imagepath: 'images/flags/lc.svg' },
  #{ correct_option: 'Islas Marshall', topic: 'Flags-9', imagepath: 'images/flags/mh.svg' },
  #{ correct_option: 'Malaui', topic: 'Flags-9', imagepath: 'images/flags/mw.svg' },
  #{ correct_option: 'Barbados', topic: 'Flags-9', imagepath: 'images/flags/bb.svg' },

  ##Demential 5

  #{ correct_option: 'Seychelles', topic: 'Flags-10', imagepath: 'images/flags/sc.svg' },
  #{ correct_option: 'Noruega', topic: 'Flags-10', imagepath: 'images/flags/no.svg' },
  #{ correct_option: 'San Martín', topic: 'Flags-10', imagepath: 'images/flags/mf.svg' },
  #{ correct_option: 'Sint Maarten', topic: 'Flags-10', imagepath: 'images/flags/sx.svg' },
  #{ correct_option: 'Guyana', topic: 'Flags-10', imagepath: 'images/flags/gy.svg' },
  #{ correct_option: 'Costa de Marfil', topic: 'Flags-10', imagepath: 'images/flags/ci.svg' },
  #{ correct_option: 'Ruanda', topic: 'Flags-10', imagepath: 'images/flags/rw.svg' },
  #{ correct_option: 'Kiribati', topic: 'Flags-10', imagepath: 'images/flags/ki.svg' },
  #{ correct_option: 'República Centroafricana', topic: 'Flags-10', imagepath: 'images/flags/cf.svg' },
  #{ correct_option: 'Burundi', topic: 'Flags-10', imagepath: 'images/flags/bi.svg' },
  #{ correct_option: 'Santo Tomé y Príncipe', topic: 'Flags-10', imagepath: 'images/flags/st.svg' },
  #{ correct_option: 'Gabón', topic: 'Flags-10', imagepath: 'images/flags/ga.svg' },
  #{ correct_option: 'Islas Åland', topic: 'Flags-10', imagepath: 'images/flags/ax.svg' },
  #{ correct_option: 'Togo', topic: 'Flags-10', imagepath: 'images/flags/tg.svg' },
  #{ correct_option: 'Zimbabue', topic: 'Flags-10', imagepath: 'images/flags/zw.svg' },
  #{ correct_option: 'Isla de Navidad', topic: 'Flags-10', imagepath: 'images/flags/cx.svg' },
  #{ correct_option: 'Bután', topic: 'Flags-10', imagepath: 'images/flags/bt.svg' },
  #{ correct_option: 'Islas Marianas del Norte', topic: 'Flags-10', imagepath: 'images/flags/mp.svg' },
  #{ correct_option: 'Islas Caimán', topic: 'Flags-10', imagepath: 'images/flags/ky.svg' },
  #{ correct_option: 'Guinea Ecuatorial', topic: 'Flags-10', imagepath: 'images/flags/gq.svg' },
  #{ correct_option: 'Islas Cook', topic: 'Flags-10', imagepath: 'images/flags/ck.svg' },
  #{ correct_option: 'Tuvalu', topic: 'Flags-10', imagepath: 'images/flags/tv.svg' },
  #{ correct_option: 'Macao', topic: 'Flags-10', imagepath: 'images/flags/mo.svg' }
]

options_data = [
  { response: 'Washington D.C.', topic: 'Flags' },
  { response: 'Shanghái', topic: 'Flags' },
  { response: 'Bombay', topic: 'Flags' },
  { response: 'San Petersburgo', topic: 'Flags' },
  { response: 'São Paulo', topic: 'Flags' },
  { response: 'Osaka', topic: 'Flags' },
  { response: 'Hamburgo', topic: 'Flags' },
  { response: 'Liverpool', topic: 'Flags' },
  { response: 'Lyon', topic: 'Flags' },
  { response: 'Ciudad de Guatemala', topic: 'Flags' },
  { response: 'Luxemburgo', topic: 'Flags' },
  { response: 'Bruselas', topic: 'Flags' },
  { response: 'Budapest', topic: 'Flags' },
  { response: 'Copenhague', topic: 'Flags' },
  { response: 'Sofía', topic: 'Flags' },
  { response: 'Zagreb', topic: 'Flags' },
  { response: 'Bucarest', topic: 'Flags' },
  { response: 'Liubliana', topic: 'Flags' },
  { response: 'Atenas', topic: 'Flags' },
  { response: 'Sucre', topic: 'Flags' },
  { response: 'Johannesburgo', topic: 'Flags' },
  { response: 'Abuja', topic: 'Flags' },
  { response: 'Alejandría', topic: 'Flags' },
  { response: 'Lahore', topic: 'Flags' },
  { response: 'Tabriz', topic: 'Flags' },
  { response: 'Hanói', topic: 'Flags' },
  { response: 'Phnom Penh', topic: 'Flags' },
  { response: 'Cracovia', topic: 'Flags' },
  { response: 'Medellín', topic: 'Flags' },
  { response: 'Caracas', topic: 'Flags' },
  { response: 'Kuala Lumpur', topic: 'Flags' },
  { response: 'Manila', topic: 'Flags' },
  { response: 'Dacca', topic: 'Flags' },
  { response: 'Lviv', topic: 'Flags' },
  { response: 'Khartoum', topic: 'Flags' },
  { response: 'Casablanca', topic: 'Flags' },
  { response: 'Nairobi', topic: 'Flags' },
  { response: 'Lima', topic: 'Flags' },
  { response: 'Santiago', topic: 'Flags' },
  { response: 'Estocolmo', topic: 'Flags' },
  { response: 'Zúrich', topic: 'Flags' },
  { response: 'Gante', topic: 'Flags' },
  { response: 'Innsbruck', topic: 'Flags' },
  { response: 'Bergen', topic: 'Flags' },
  { response: 'Haifa', topic: 'Flags' },
  { response: 'Basora', topic: 'Flags' },
  { response: 'Dubái', topic: 'Flags' },
  { response: 'Madeira', topic: 'Flags' },
  { response: 'Johor Bahru', topic: 'Flags' },
  { response: 'Salónica', topic: 'Flags' },
  { response: 'Aarhus', topic: 'Flags' },
  { response: 'Tampere', topic: 'Flags' },
  { response: 'Győr', topic: 'Flags' },
  { response: 'Olomouc', topic: 'Flags' },
  { response: 'Constanza', topic: 'Flags' },
  { response: 'Niš', topic: 'Flags' },
  { response: 'Plovdiv', topic: 'Flags' },
  { response: 'Košice', topic: 'Flags' },
  { response: 'Zadar', topic: 'Flags' },
  { response: 'Tarija', topic: 'Flags' },        
  { response: 'Una entidad política soberana con un territorio definido y un gobierno', topic: 'Physical Geography' },
  { response: 'Una montaña o colina formada por la acumulación de materiales expulsados desde el interior de la Tierra', topic: 'Physical Geography' },
  { response: 'Centro administrativo y político de un país o estado', topic: 'Political Geography' },
  { response: 'Un país es un área geográfica que no tiene límites definidos y está habitada por múltiples grupos étnicos.', topic: 'Physical Geography' },
  { response: 'Un volcán es una formación geológica compuesta por capas de rocas sedimentarias.', topic: 'Physical Geography' },
  { response: 'Una capital en geografía se define como la ciudad más grande de un país.', topic: 'Physical Geography' },
  { response: 'Un desierto es una región geográfica caracterizada por su abundante vegetación y altos niveles de precipitación.', topic: 'Physical Geography' },
  { response: 'Un istmo es una cordillera montañosa que divide dos océanos.', topic: 'Physical Geography' },
  { response: 'Un archipiélago se refiere a una serie de montañas próximas entre sí en medio de un océano.', topic: 'Physical Geography' },
  { response: 'Un golfo es una formación geográfica compuesta por tierras altas y montañas.', topic: 'Physical Geography' },
  { response: 'Una isla es una extensión de tierra que no está rodeada por agua.', topic: 'Physical Geography' },
  { response: 'Un río es una formación geológica que se encuentra bajo tierra.', topic: 'Physical Geography' },
  { response: 'Las placas tectónicas en geografía física son formaciones de hielo en los polos terrestres.', topic: 'Physical Geography' }, 
  { question: '¿Qué es la meteorización?', correct_option: 'El proceso de descomposición y desgaste de rocas y suelo debido a factores como el clima y la acción biológica', topic: 'Physical Geography' },
  { question: '¿Qué son las montañas?', correct_option: 'Elevaciones naturales del terreno que se caracterizan por su altura y relieve escarpado', topic: 'Physical Geography' },
  { question: '¿Qué es la tundra?', correct_option: 'Un bioma frío y árido caracterizado por suelos congelados y vegetación escasa, como musgos y líquenes', topic: 'Physical Geography' },
  { question: '¿Cuál es el proceso de erosión más común en las costas?', correct_option: 'La acción del oleaje y las corrientes marinas', topic: 'Physical Geography' },
  { question: '¿Qué es el permafrost?', correct_option: 'Suelo permanentemente congelado que se encuentra en regiones frías, como el Ártico', topic: 'Physical Geography' },
  { question: '¿Qué es un acuífero?', correct_option: 'Una formación geológica subterránea que almacena y transmite agua subterránea', topic: 'Physical Geography' },
  { question: '¿Cuál es el efecto de la deforestación en el medio ambiente?', correct_option: 'La pérdida de biodiversidad, el cambio climático y la degradación del suelo', topic: 'Physical Geography' },
  { question: '¿Qué son los glaciares?', correct_option: 'Grandes masas de hielo que se forman en tierra y se mueven lentamente debido a la gravedad', topic: 'Physical Geography' },
  { question: '¿Qué es el ciclo del agua?', correct_option: 'El proceso continuo de evaporación, condensación, precipitación y escorrentía que mueve el agua a través del ambiente terrestre', topic: 'Physical Geography' },
  { question: '¿Qué es un ecosistema?', correct_option: 'Una comunidad biológica de organismos vivos interactuando con su entorno físico', topic: 'Physical Geography' },
  { response: 'La población de un área geográfica se refiere al número total de edificios en esa área.', topic: 'Human Geography' },
  { response: 'La cultura en geografía humana se define como la forma en que las personas se mueven y viajan dentro de una región específica.', topic: 'Human Geography' },
  { response: 'La urbanización se refiere al proceso de reducción del tamaño de las áreas urbanas.', topic: 'Human Geography' },
  { response: 'La globalización se refiere a la tendencia de las culturas a permanecer aisladas y sin influencia externa.', topic: 'Human Geography' },
  { response: 'La demografía es el estudio de los patrones climáticos en una región determinada.', topic: 'Human Geography' },
  { response: 'La industrialización es el proceso de transformar una sociedad basada en la industria en una sociedad basada en la agricultura.', topic: 'Human Geography' },
  { response: 'La pobreza se define como el acceso abundante a recursos básicos como alimentos, vivienda y educación.', topic: 'Human Geography' },
  { response: 'La diversidad cultural se refiere a la homogeneidad cultural dentro de una sociedad.', topic: 'Human Geography' },
  { response: 'La gentrificación es el proceso de renovación urbana que a menudo resulta en la mejora de la calidad de vida de los residentes de bajos ingresos.', topic: 'Human Geography' },
  { response: 'La migración se refiere al proceso de inmovilización de personas dentro de un mismo lugar.', topic: 'Human Geography' },  
  { response: 'Es un continente pequeño ubicado en el hemisferio sur, rodeado principalmente por el océano Índico.', topic: 'Continents' },
  { response: 'Este continente se encuentra en el hemisferio norte y está rodeado principalmente por el océano Atlántico y el océano Pacífico.', topic: 'Continents' },
  { response: 'Ubicado en el hemisferio sur, este continente limita con Europa y África al norte.', topic: 'Continents' },
  { response: 'Es el continente más pequeño del mundo y está rodeado principalmente por el océano Pacífico.', topic: 'Continents' },
  { response: 'Es el océano más pequeño y se encuentra en el hemisferio sur, rodeado principalmente por Europa y África.', topic: 'Oceans' },
  { response: 'Se encuentra entre América del Norte y América del Sur, y es conocido por ser el océano más frío del mundo.', topic: 'Oceans' },
  { response: 'Este océano se encuentra principalmente en el hemisferio sur y limita con Asia y Oceanía.', topic: 'Oceans' },
  { response: 'Ubicado en el hemisferio norte, este océano está rodeado por Australia, África y América del Sur.', topic: 'Oceans' },
  { response: 'Un grupo de personas que viven juntas en un área geográfica', topic: 'Political Geography' },
  { response: 'Un conjunto de leyes y regulaciones que rigen un país', topic: 'Political Geography' },
  { response: 'Una estructura física que separa dos países', topic: 'Political Geography' },
  { response: 'Un sistema de gobierno en el que el pueblo elige a sus líderes mediante elecciones directas', topic: 'Political Geography' },
  { response: 'Un documento histórico que registra eventos políticos importantes', topic: 'Political Geography' },
  { response: 'El proceso de crear nuevas leyes y políticas dentro de un país', topic: 'Political Geography' },
  { response: 'Una forma de gobierno en la que los militares tienen el control político', topic: 'Political Geography' },
  { response: 'Una organización religiosa que tiene influencia sobre las decisiones políticas de un país', topic: 'Political Geography' },
  { response: 'Un tipo de gobierno en el que las decisiones políticas se toman de manera descentralizada', topic: 'Political Geography' }
]

options_data.each do |o_data| 
  topic = Topic.find_by(topic: o_data[:topic])
  next unless topic

  Option.find_or_create_by(response: o_data[:response], topics_id: topic.id)
end

niveles = ["Nivel 1", "Nivel 2", "Nivel 3", "Nivel 4", "Nivel 5", "Nivel 6"]

niveles.each_with_index do |nivel_name, index|
  Level.create(number: index + 1, name: nivel_name)
end

(1..6).each do |i|
  lesson = Lesson.find_by(title: "Flags")
  level = Level.find_by(number: i)
  Exam.create(name: "Banderas #{i}", lesson_id: lesson.id, level: level)
end

(1..6).each do |i|
  lesson = Lesson.find_by(title: "Physical Geography")
  level = Level.find_by(number: i)
  Exam.create(name: "Geografía Física #{i}", lesson_id: lesson.id, level: level)
end

(1..6).each do |i|
  lesson = Lesson.find_by(title: "Human Geography")
  level = Level.find_by(number: i)
  Exam.create(name: "Geografía Humana #{i}", lesson_id: lesson.id, level: level)
end

(1..6).each do |i|
  lesson = Lesson.find_by(title: "Continents")
  level = Level.find_by(number: i)
  Exam.create(name: "Continentes, Océanos y Mares #{i}", lesson_id: lesson.id, level: level)
end

(1..6).each do |i|
  lesson = Lesson.find_by(title: "Capitals")
  level = Level.find_by(number: i)
  Exam.create(name: "Capitales #{i}", lesson_id: lesson.id, level: level)
end

(1..6).each do |i|
  lesson = Lesson.find_by(title: "Political Geography")
  level = Level.find_by(number: i)
  Exam.create(name: "Geografía Política #{i}", lesson_id: lesson.id, level: level)
end

questions_data.each do |q_data|
  topic = Topic.find_by(topic: q_data[:topic])
  next unless topic

  correct_option = Option.find_or_create_by(response: q_data[:correct_option], topics_id: topic.id)
  
  if (q_data[:imagepath] != nil)
    question = Question.find_or_create_by(question: '¿A qué país pertenece esta bandera?', topics_id: topic.id)    
    Qa.create!(questions_id: question.id, options_id: correct_option.id, imagepath: q_data[:imagepath])
  else
    question = Question.create!(question: q_data[:question], topics_id: topic.id)
    exam = Exam.find_by(name: q_data[:exam])
    Qa.create!(questions_id: question.id, options_id: correct_option.id, imagepath: q_data[:imagepath], exam_id: exam&.id)
  end
  
end
