source 'https://rubygems.org'

gem "sinatra"
gem "sinatra-activerecord"
gem 'sqlite3', '~> 1.4'
gem "rake"
gem "bcrypt"
gem "rackup"
gem "dotenv"
gem 'simplecov', require: false
group :development, :test do
  gem 'rspec'
  gem 'rspec-sinatra'
  gem 'rack-test'
  gem 'database_cleaner-active_record'
end