# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt'
gem 'dotenv'
gem 'rackup'
gem 'rake'
gem 'rubocop', require: false
gem 'simplecov', require: false
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.4'

group :development, :test do
  gem 'database_cleaner-active_record'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-sinatra'
end
